###
http://localhost:3000/v1/events

###
http://localhost:3000/v1/events/72ce56d05af0951566b7b538

###
http://localhost:3000/v1/events?_end=12&_start=0

###
https://api.finefoods.refine.dev/events?_end=12&_start=0

###
PATCH http://localhost:3000/v1/events/9124f736dd386fe753165597
Content-Type: application/json

{"title":"🍟 Starters 123231","description":"","isActive":false,"images":[]}

###
POST http://localhost:3000/v1/events
Content-Type: application/json

{"title":"🍟 Starters ttt","description":"","isActive":false,"images":[]}

